def test_strategy(strategy):

    print("df", strategy.df.head())
    print("class of df", type(strategy.df.head()))
    print("start_wallet.a", strategy.start_wallet.a)
    print("start_wallet.b", strategy.start_wallet.b)
    print("end_wallet.a", strategy.end_wallet.a)
    print("end_wallet.b", strategy.end_wallet.b)
    print("class of end_wallet", type(strategy.end_wallet))
    print("get_operations", strategy.get_operations().head())
    print("class of get_opeations", type(strategy.get_operations().head()))
    print("get_n_operations", strategy.get_n_operations())
    print("class of get_n_opeations", type(strategy.get_n_operations()))
    print("get_n_operations_by_hour", strategy.get_n_operations_by_hour())
    print("class of get_n_operations_by_hour", type(strategy.get_n_operations_by_hour()))
    print("get_mean_operation_time", strategy.get_mean_operation_time())
    print("class of get_mean_operation_time", type(strategy.get_mean_operation_time()))
    print("get_n_good_operations", strategy.get_n_good_operations())
    print("class of get_n_good_operations", type(strategy.get_n_good_operations()))
    print("get_n_bad_operations", strategy.get_n_bad_operations())
    print("class of get_n_bad_operations", type(strategy.get_n_bad_operations()))
    print("get_periods", strategy.get_periods())
    print("class of get_periods", type(strategy.get_periods()))
    print("get_profitabilities", strategy.get_profitabilities())
    print("class of get_profitabilities", type(strategy.get_profitabilities()))
